### ISSUE TITLE
 'TextCardExporter' object has no attribute 'count'

### ISSUE THREAD

**Issue by L-M-Sherlock** [Arthur-Milchior/anki-export-from-browser#2]
I exported my cards in browser as Cards in Plain Text, then an error occured.

Debug info:
Anki 2.1.9 (ae67c976) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
  File "C:\Users\L.M.Sherlock\AppData\Roaming\Anki2\addons21\1983204951\exportFromBrowser.py", line 149, in accept
    self.exporter.count) % self.exporter.count
<class 'AttributeError'>: 'TextCardExporter' object has no attribute 'count'

**Comment by Arthur-Milchior** [comment]
thank you for letting me now. I guess I haven't tested enough, I actually never export in plain text

**Comment by Arthur-Milchior** [comment]
New version works on my computer for exporting cards. It's uploaded on ankiweb. Update your addon and test again please.

**Comment by L-M-Sherlock** [comment]
It works well now! Thanks a lot!
