### ISSUE TITLE
[question] default separator in csv

### ISSUE THREAD

**Issue by omega3** [Arthur-Milchior/anki-export-from-browser#4]
Can you tell me what is default separator used in csv export? 
I want to open it in LibreOffice Calc and have each Anki field in separate column, but I can't figure out what is the proper separator. Neither tab, nor comma, nor semicolon works. 
Does it save as UTF-8 or another?
Would it be possible to set individual separator?
 Here is example how tab is trying to open:
https://imgur.com/GoCAdSC

**Comment by Arthur-Milchior** [comment]
Comma. It, exactly the same CZV than the one you have when you export a
deck. The only difference this addon makes is the set of selected notes,
not the output format
Your screensht looks perfect, you just have to select your local version of
comma. Which language is it by curiosity ?

**Comment by omega3** [comment]
> Which language is it by curiosity ? 
Polish.

Ok. My fault. I forgot that I had different note types in this selection. That's why it looked messy to me, but it wasn't.

**Comment by Arthur-Milchior** [comment]
I just realized that anki does not have CSV export by default. So I guess you are using either https://ankiweb.net/shared/info/1207511854 or https://ankiweb.net/shared/info/1478130872
you should make the bug report to them. Clearly, it would make more sens to separate different notes
